### ISSUE TITLE
Connection refused on ruby

### ISSUE THREAD

**Issue by yorshidosone** [ecin/zxing.rb#6]
I am currently using zxing to decode my qr codes, it works perfectly on development but on production:

ActionView::Template::Error (druby://127.0.0.1:35867 - #<Errno::ECONNREFUSED: Connection refused - connect(2)>):
<% if (ZXing.decode "public/assets/#{current_user.user_name.downcase}_bdd.jpg").nil? %>

It is woth to mention that A FEW TIMES it works, but most of the time it is not, I added a text for debug, just to see at what point it was failing and then it works, then i tried again later with no changes on the code and it give the "connection refused" error.

EDIT: Ok, I kind of narrowed down a little, it works after i restart my server, but only for five minutes or so, after that it gave me the described error.

**Comment by jgdavey** [comment]
Are you using MRI? Also, what is your production stack like? Are you using a forking webserver like Unicorn or passenger?

**Comment by yorshidosone** [comment]
Sorry for the lack of details, I'm with ruby 1.9.2 using jruby-jars 1.7.4, working with passenger and apache on ubuntu server and for deploy, capistrano, what I've found odd is the fact that it works on production environment for a couple of minutes after the restart of the server, then it comes this error and it won't go away unless i restart the server again.

**Comment by jgdavey** [comment]
This is almost certainly due to a resource limit being hit. Since passenger uses a forking multi-process model, each process would potentially be spinning up its own dRB server, which uses its own JVM instance. Multiple JVMs running would exhaust system resources on even robust servers.

On master, I've introduced the ability to explicitly set `ZXING_PORT`. By setting/exporting, you can explicitly choose a free TCP port, and all forked processes will reuse the same server.

``` bash
export ZXING_PORT=9998
```

**Comment by yorshidosone** [comment]
Thanks, but only one more thing, where do i put the export instruction? I tried on the production.rb as well on application.rb with little success, it only gets ignored.

**Comment by jgdavey** [comment]
That will likely depend on your setup. You might check out Passenger's documentation on the subject. http://www.modrails.com/documentation/Users%20guide%20Apache.html#about_environment_variables

**Comment by jjacquay712** [comment]
Just to note, in order to get zxing.rb working with **mod_passenger**:

You must set the environment variable in your httpd.conf file to make all forked processes use the same JVM (and configure selinux to allow [httpd] binding a socket if it's enabled).

```
SetEnv ZXING_PORT 9998
```

And also disable mod_passenger timeouts:

```
PassengerMaxPreloaderIdleTime 0
PassengerPoolIdleTime 0
```

Passenger docs can be found here:
https://www.phusionpassenger.com/library/config/apache/reference/#passengerpoolidletime
https://www.phusionpassenger.com/library/config/apache/reference/#passengermaxpreloaderidletime

With these config changes to httpd.conf I was able to fix this error that occurred 5 minutes after apache was restarted:

```
DRb::DRbConnError - druby://127.0.0.1:9998 - #<Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 9998>:
```

**Comment by ecin** [comment]
Thanks for the docs, @jjacquay712!
